- set_fact:
    sf_final_status: "unknown"
    sf_final_cluster_version: "unknown"
    sf_cluster_member_list: []

- name: Load validation tasks for prerequisites
  include_tasks: prechecks.yml

- name: Load set-cluster-name tasks
  include_tasks: set-cluster-name.yml
  args:
    apply:
      delegate_to: localhost
      any_errors_fatal: True

- name: Load create-cluster tasks
  include_tasks: create-cluster.yml

- name: Add all available drives if so desired
  when: sf_auto_add_available_drives is undefined or
    (sf_auto_add_available_drives is defined and sf_auto_add_available_drives)
  include_tasks: add-drives.yml

- debug:
    msg: "Cluster creation was successful. Current cluster version: {{ sf_final_cluster_version }}. Please go to https://{{ MVIP }} to check any cluster alerts."
  when: sf_final_status == "success"
  run_once: True
